services:
  - name: api-similaridade
    type: web
    runtime: python              # usa o build nativo Python do Render
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --cache-dir="$HOME/.cache/pip" -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    # instruções de cache para acelerar builds futuros
    build:
      # Render vai salvar/restaurar essa pasta entre deploys
      cachePaths:
        - ~/.cache/pip