services:
  - name: api-similaridade
    type: web
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --no-deps torch==2.7.1+cpu --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('intfloat/e5-base-v2')"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000