services:
  - type: web
    name: api-similaridade
    runtime: python              # usa o build nativo Python do Render
    branch: main
    buildCommand: |
      pip install --upgrade pip
      # força o pip a usar ~/.cache/pip como cache de pacotes
      pip install --cache-dir="$HOME/.cache/pip" -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    # instruções de cache para acelerar builds futuros
    build:
      # Render vai salvar/restaurar essa pasta entre deploys
      cachePaths:
        - ~/.cache/pip